version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - SPARK_WORKER_COUNT=8
      - OPENSEARCH_HOST=opensearch-node
      - OPENSEARCH_PORT=9200
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KEYCLOAK_URL=${KEYCLOAK_BASE_URL}
#      - KEYCLOAK_URL=http://host.docker.internal:8180
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - AUDIT_LOG_EVENTS_EXCHANGE=${AUDIT_LOG_EVENTS_EXCHANGE}
      - AUDIT_LOG_TRACE_ID_HTTP_HEADER=${AUDIT_LOG_TRACE_ID_HTTP_HEADER}
    ports:
      - 5000:5000
    volumes:
      - ./src:/opt/elastictm/src
      - ./conf:/opt/elastictm/conf
